# Generated by Django 2.2 on 2020-04-15 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devcamp_social', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('user', models.CharField(default='anonymous', max_length=80)),
                ('posted_on', models.DateTimeField(verbose_name='date commented')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devcamp_social.UserPost')),
            ],
        ),
    ]
